[package]
name = "trade_aggregation"
version = "3.0.0"
authors = ["MathisWellmann <wellmannmathis@gmail.com>"]
edition = "2021"
license-file = "LICENSE"
description = "Aggregate raw trades into candles using different methods"
repository = "https://github.com/MathisWellmann/trade_aggregation-rs"
readme = "README.md"
keywords = [
    "trading",
    "candles",
]
categories = [
    "algorithms"
]
exclude = [
    "/img",
    "/.idea",
]

[dependencies]
csv = "^1"
chrono = "^0.4"
serde = {version = "^1", features = ["derive"] }
thiserror = "^1"

trade_aggregation_derive = { version = "^0.1.0", path = "trade_aggregation_derive" }

[dev-dependencies]
time_series_generator = "^0.2"
round = "^0.1"
criterion = "^0.3"

[[bench]]
name = "candle_aggregation"
harness = false