[package]
name = "trade_aggregation"
version = "1.0.2"
authors = ["MathisWellmann <wellmannmathis@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
description = "Aggregate raw trades into candles using different methods"
repository = "https://github.com/MathisWellmann/trade_aggregation-rs"
readme = "README.md"
keywords = [
    "trading",
    "candles",
]
categories = [
    "algorithms"
]
exclude = [
    "/img",
    "/.idea",
]

[dependencies]
csv = "1.1"
chrono = "0.4.11"
serde = {version = "1.0.125", features = ["derive"] }

[dev-dependencies]
time_series_generator = "0.2"
round = "0.1.0"
