[package]
name = "trade_aggregation"
version = "0.1.0"
authors = ["MathisWellmann <wellmannmathis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rust_timeseries_generator = { git = "https://github.com/MathisWellmann/rust_timeseries_generator"}
csv = "1.1"
